import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import "react-loading-skeleton/dist/skeleton.css";
import "@rainbow-me/rainbowkit/styles.css";
import { headers } from "next/headers";
import Providers from "./providers";
import GlobalHeader from "./components/Navigation/GlobalHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = headers().get("cookie");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers cookie={cookie}>
          {/* <GlobalHeader /> */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
